
development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: escola_development
  pool: 5
  username: escola
  password: escola
  
test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: escola_test
  pool: 5
  username: escola
  password: escola

production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: escola_production
  pool: 5
  username: escola
  password: escola
